export const SEARCH_MOVIE_START = 'SEARCH_MOVIE_START';
export const SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';

export const SEARCH_DETAIL_MOVIE_START = 'SEARCH_DETAIL_MOVIE_START';
export const SEARCH_DETAIL_MOVIE_ERROR = 'SEARCH_DETAIL_MOVIE_ERROR';
export const SEARCH_DETAIL_MOVIE_SUCCESS = 'SEARCH_DETAIL_MOVIE_SUCCESS';
